trigger:
- main

resources:
- repo: self

variables:
  imageRepository: 'elywen/simplon'
  imageName: 'voting'
  dockerfilePath: './Dockerfile'
  kubernetesServiceEndpoint: 'KlusterLunaConnection'
  canaryTag: 'canary'

# Build the docker image
stages:
- stage: Build
  jobs:
  - job: BuildAndPush
    displayName: 'Build and Push to DockerHub'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHubConnection'
        repository: 'elywen/simplon'
        command: 'buildAndPush'
        Dockerfile: './Dockerfile'
        tags: 'latest'

# Deploy to QA
- stage: DeployQA
  dependsOn: Build
  jobs:
  - job: DeployToQA
    displayName: 'Deploy to QA'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Kubernetes@1
      displayName: Deploy to QA
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: '$(kubernetesServiceEndpoint)'
        namespace: 'qa'
        command: 'apply'
        arguments: '-f ./k8s/deployment.yaml'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Container Registry'
        dockerRegistryEndpoint: 'DockerHubConnection'

# Test QA service
- stage: TestQA
  dependsOn: DeployQA
  jobs:
  - job: TestQAService
    displayName: 'Test QA Service'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        curl https://kittyqa.simplon-ely.space/
      displayName: Test QA Service with curl

# Signout
- stage: SignOut
  jobs:
    - job: SigningOut
      displayName: 'Elywen Signing Out'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: CmdLine@2
        inputs:
          script: |
            echo Thank you for using my Pipeline.
            echo
            echo Elywen is wishing you the best possible day !